CREATE TABLE `client` (
	`codeclien't` VARCHAR(15) NULL DEFAULT NULL,
	`nomclient` VARCHAR(255) NULL DEFAULT NULL,
	`adresse` VARCHAR(255) NULL DEFAULT NULL,
	`codepostal` VARCHAR(5) NULL DEFAULT NULL,
	`ville` VARCHAR(80) NULL DEFAULT NULL,
	`tel` VARCHAR(15) NULL DEFAULT NULL,
	`email` VARCHAR(70) NULL DEFAULT NULL,
    `datenaissance` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`codeclient`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;
